version: 2

builds:
  - binary: koshime
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{ .Version }}
      - -X main.commitSha={{ .ShortCommit }}
      - -X main.buildDate={{ .Date }}
    flags:
      - -trimpath
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
           - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^tdd"
      - "^test"
  groups:
    - title: New
      regexp: "^feat[(\\w)]*:+.*$"
      order: 100

    - title: Performance
      regexp: "^perf[(\\w)]*:+.*$"
      order: 150

    - title: Changes
      regexp: "^refactor[(\\w)]*:+.*$"
      order: 200

    - title: "Fixes"
      regexp: "^fix[(\\w)]*:+.*$"
      order: 300

    - title: "Docs"
      regexp: "^docs[(\\w)]*:+.*$"
      order: 400

    - title: "Maintenance"
      regexp: "^chore[(\\w)]*:+.*$"
      order: 600

    - title: "Other"
      order: 999
