version: 2

builds:
  - binary: 'koshime_{{ .Os }}_build-{{ slice (printf "%d" .Timestamp) 0 9 }}'
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{ .Version }}
      - -X main.commitSha={{ .ShortCommit }}
      - -X main.buildDate={{ .Date }}
    flags:
      - -trimpath
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true

checksum:
  disable: true

# Explicitly disable archive generation for dev workflows
archives:
  - formats:
      - binary
