words = [
    "Asahi",
    "Bahamut",
    "Bilibili",
    "Bittorrent",
    "Bittorrent's",
    "Cutset",
    "Esc",
    "Fansub",
    "HIDIVE",
    "Kitsu",
    "Nyaa",
    "ONA",
    "QURL",
    "Romaji",
    "Tosho",
    "adn",
    "aed",
    "amzn",
    "animetosho",
    "atmos",
    "avc",
    "baha",
    "bdrip",
    "bili",
    "bluray",
    "bstation",
    "ddp",
    "dsnp",
    "dvdrip",
    "eac",
    "fansubs",
    "hevc",
    "koshime",
    "qbittorrent",
    "qbt",
    "sdr",
    "truehd",
    "viki",
    "vnd",
    "webrip",
]

ignore_paths = [
    "*.yml"
]
