words = [
    "Asahi",
    "Bahamut",
    "Bilibili",
    "Bittorrent",
    "Bittorrent's",
    "Boku",
    "Cutset",
    "Erai",
    "Esc",
    "Fansub",
    "HIDIVE",
    "Kitsu",
    "Kokaku",
    "Kokakunoou",
    "Kyojin",
    "Kyoujin",
    "NFO",
    "Naruto",
    "Nyaa",
    "ONA",
    "QURL",
    "Romaji",
    "Shingeki",
    "Tosho",
    "WRONLY",
    "adn",
    "aed",
    "amzn",
    "animetosho",
    "atmos",
    "avc",
    "baha",
    "bdrip",
    "bili",
    "bluray",
    "bstation",
    "bubbletea",
    "ddp",
    "dsnp",
    "dvdrip",
    "eac",
    "fansubs",
    "hevc",
    "koshime",
    "qbittorrent",
    "qbt",
    "raws",
    "sdr",
    "truehd",
    "viki",
    "vnd",
    "webrip",
]
ignore_paths = ["*.yml"]
