package qbittorrent

import (
	"encoding/json"
	"errors"
	"fmt"
	"net"
	"net/http"
	"net/url"
	"os"
	"syscall"

	"github.com/Jaeiya/koshime/lib/utils"
	"golang.org/x/sys/windows"
)

var (
	isLoggedIn     = false
	qbtPort        = "8080"
	errNotLoggedIn = fmt.Errorf("you need to be logged into qbittorrent")
	errConnRefused = fmt.Errorf("cannot connect to qbittorrent")
)

func Login(password string, port string) error {
	var httpUtils utils.Http
	if port != "" {
		qbtPort = port
	}
	resp, err := httpUtils.PostForm(
		getBaseURL()+"/auth/login",
		url.Values{"username": {"admin"}, "password": {password}},
	)
	if err != nil {
		if isConnectionRefused(err) {
			return errConnRefused
		}
		return err
	}

	if resp.StatusCode >= 400 {
		return fmt.Errorf("could not login: %s", string(resp.Body))
	}

	isLoggedIn = true
	return nil
}

func AddFeed(feedURL string, name string) error {
	if !isLoggedIn {
		return errNotLoggedIn
	}

	var httpUtils utils.Http
	resp, err := httpUtils.PostForm(getBaseURL()+"/rss/addFeed", url.Values{
		"url":  {feedURL},
		"path": {name},
	})
	if err != nil {
		return err
	}

	if resp.StatusCode >= 400 {
		return fmt.Errorf("failed to add feed: %s", string(resp.Body))
	}
	return nil
}

func GetFeeds() ([]RSSFeedItem, error) {
	if !isLoggedIn {
		return nil, errNotLoggedIn
	}

	httpUtils := utils.Http{}
	req, _ := http.NewRequest("GET", getBaseURL()+"/rss/items", nil)
	resp, err := httpUtils.Do(req, "application/json", "")
	if err != nil {
		return nil, err
	}

	if resp.StatusCode >= 400 {
		return nil, fmt.Errorf("failed to get rss items: %s", string(resp.Body))
	}

	var feeds map[string]RSSFeedData
	if err := json.Unmarshal(resp.Body, &feeds); err != nil {
		panic(err)
	}

	items := make([]RSSFeedItem, 0, len(feeds))
	for name, feed := range feeds {
		items = append(items, RSSFeedItem{name, feed.UID, feed.URL})
	}

	return items, nil
}

func getBaseURL() string {
	return "http://localhost:" + qbtPort + "/api/v2"
}

// isConnectionRefused has been entirely generated by AI. I
// have no idea where to even begin to figure out how to
// handle this error "properly" myself and I don't want
// to think about it.
//
// This is strictly a convenience method and might only
// work on windows.
func isConnectionRefused(err error) bool {
	var urlErr *url.Error
	if errors.As(err, &urlErr) {
		err = urlErr.Err
	}

	var opErr *net.OpError
	if !errors.As(err, &opErr) {
		return false
	}

	sysErr, ok := opErr.Err.(*os.SyscallError)
	if !ok {
		return false
	}

	// check standard syscall.Errno
	if errno, ok := sysErr.Err.(syscall.Errno); ok && errno == syscall.ECONNREFUSED {
		return true
	}

	// check windows-specific Errno
	if wErr, ok := sysErr.Err.(windows.Errno); ok && wErr == windows.WSAECONNREFUSED {
		return true
	}

	return false
}
